# Home directory. 
#
#HOME = ""

ANDROID_SDK_HOME = HOME + "/Library/Android/sdk"
ANDROID_NDK_HOME = HOME + "/Library/Android/sdk/ndk-bundle"

# Load Closure repository and build definitions.
git_repository(
    name = "io_bazel_rules_closure",
    remote = "https://github.com/bazelbuild/rules_closure.git",
    commit = "329ce4674350ce8c4e7edea6dae3c2841822e0db",
)

load("@io_bazel_rules_closure//closure:defs.bzl", "closure_repositories")
closure_repositories()

# Load Golang repository and build definitions.
git_repository(
    name = "io_bazel_rules_go",
    remote = "https://github.com/bazelbuild/rules_go.git",
    commit = "373feb67001252371054c3388291661352c4eb90",
)

load('@io_bazel_rules_go//go:def.bzl', 'go_repositories')
go_repositories()


android_sdk_repository(
    name = "androidsdk",
    # Replace with path to Android SDK on your system
    path = ANDROID_SDK_HOME,
    # Replace with the Android SDK API level
    api_level = 23,
    # Replace with the version in sdk/build-tools/
    build_tools_version="23.0.0"
)

#android_ndk_repository(
#    name = "androidndk",
#    # Replace with path to Android NDK on your system
#    path = ANDROID_NDK_HOME,
#    # Replace with the Android NDK API level
#    api_level = 21
#)
