# Load Closure repository and build definitions.
git_repository(
    name = "io_bazel_rules_closure",
    remote = "https://github.com/bazelbuild/rules_closure.git",
    tag = "0.0.1",
)

load("@io_bazel_rules_closure//closure:defs.bzl", "closure_repositories")
closure_repositories()

# Load Golang repository and build definitions.
git_repository(
    name = "io_bazel_rules_go",
    remote = "https://github.com/bazelbuild/rules_go.git",
    commit = "373feb67001252371054c3388291661352c4eb90",
)

load('@io_bazel_rules_go//go:def.bzl', 'go_repositories')
go_repositories()
